-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CognitiveProcessDesigner/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE cpd_orphaned_description_pages (
  page_title VARCHAR(255) NOT NULL,
  process VARCHAR(255) NOT NULL,
  process_rev INT NOT NULL
);

CREATE UNIQUE INDEX page_title ON cpd_orphaned_description_pages (page_title);
