-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CognitiveProcessDesigner/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE IF NOT EXISTS /*_*/cpd_element_connections (
  from_page VARCHAR(255) NOT NULL,
  to_page VARCHAR(255) NOT NULL,
  process VARCHAR(255) NOT NULL,
  from_type VARCHAR(255) NOT NULL,
  to_type VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS /*_*/cpd_orphaned_description_pages (
  page_title VARCHAR(255) NOT NULL,
  process VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX page_title ON /*_*/cpd_orphaned_description_pages (page_title);
